/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusRouteImport } from './routes/bus'
import { Route as DanceRouteImport } from './routes/dance'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoveRouteImport } from './routes/love'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as SalonRouteImport } from './routes/salon'
import { Route as SearchRouteImport } from './routes/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const DanceRoute = DanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/dance': typeof DanceRoute
  '/download': typeof DownloadRoute
  '/love': typeof LoveRoute
  '/playlist': typeof PlaylistRoute
  '/salon': typeof SalonRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/dance': typeof DanceRoute
  '/download': typeof DownloadRoute
  '/love': typeof LoveRoute
  '/playlist': typeof PlaylistRoute
  '/salon': typeof SalonRoute
  '/search': typeof SearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/dance': typeof DanceRoute
  '/download': typeof DownloadRoute
  '/love': typeof LoveRoute
  '/playlist': typeof PlaylistRoute
  '/salon': typeof SalonRoute
  '/search': typeof SearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus'
    | '/dance'
    | '/download'
    | '/love'
    | '/playlist'
    | '/salon'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/dance'
    | '/download'
    | '/love'
    | '/playlist'
    | '/salon'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/bus'
    | '/dance'
    | '/download'
    | '/love'
    | '/playlist'
    | '/salon'
    | '/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusRoute: typeof BusRoute
  DanceRoute: typeof DanceRoute
  DownloadRoute: typeof DownloadRoute
  LoveRoute: typeof LoveRoute
  PlaylistRoute: typeof PlaylistRoute
  SalonRoute: typeof SalonRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dance': {
      id: '/dance'
      path: '/dance'
      fullPath: '/dance'
      preLoaderRoute: typeof DanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusRoute: BusRoute,
  DanceRoute: DanceRoute,
  DownloadRoute: DownloadRoute,
  LoveRoute: LoveRoute,
  PlaylistRoute: PlaylistRoute,
  SalonRoute: SalonRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
